/*
    ekern_bad.cpp
    Copyright (C) 2006 zg

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
*/

#include <e32std.h>

EXPORT_C void ekern_1(void) {}
//EXPORT_C void ekern_2(void) {}
//EXPORT_C void ekern_3(void) {}
EXPORT_C void ekern_4(void) {}
EXPORT_C void ekern_5(void) {}
EXPORT_C void ekern_6(void) {}
EXPORT_C void ekern_7(void) {}
EXPORT_C void ekern_8(void) {}
//EXPORT_C void ekern_9(void) {}
//EXPORT_C void ekern_10(void) {}
//EXPORT_C void ekern_11(void) {}
//EXPORT_C void ekern_12(void) {}
EXPORT_C void ekern_13(void) {}
//EXPORT_C void ekern_14(void) {}
//EXPORT_C void ekern_15(void) {}
EXPORT_C void ekern_16(void) {}
EXPORT_C void ekern_17(void) {}
EXPORT_C void ekern_18(void) {}
EXPORT_C void ekern_19(void) {}
EXPORT_C void ekern_20(void) {}
EXPORT_C void ekern_21(void) {}
EXPORT_C void ekern_22(void) {}
EXPORT_C void ekern_23(void) {}
EXPORT_C void ekern_24(void) {}
EXPORT_C void ekern_25(void) {}
EXPORT_C void ekern_26(void) {}
EXPORT_C void ekern_27(void) {}
EXPORT_C void ekern_28(void) {}
EXPORT_C void ekern_29(void) {}
EXPORT_C void ekern_30(void) {}
EXPORT_C void ekern_31(void) {}
EXPORT_C void ekern_32(void) {}
EXPORT_C void ekern_33(void) {}
EXPORT_C void ekern_34(void) {}
EXPORT_C void ekern_35(void) {}
EXPORT_C void ekern_36(void) {}
EXPORT_C void ekern_37(void) {}
//EXPORT_C void ekern_38(void) {}
EXPORT_C void ekern_39(void) {}
EXPORT_C void ekern_40(void) {}
EXPORT_C void ekern_41(void) {}
EXPORT_C void ekern_42(void) {}
//EXPORT_C void ekern_43(void) {}
//EXPORT_C void ekern_44(void) {}
//EXPORT_C void ekern_45(void) {}
//EXPORT_C void ekern_46(void) {}
EXPORT_C void ekern_47(void) {}
EXPORT_C void ekern_48(void) {}
//EXPORT_C void ekern_49(void) {}
//EXPORT_C void ekern_50(void) {}
//EXPORT_C void ekern_51(void) {}
EXPORT_C void ekern_52(void) {}
EXPORT_C void ekern_53(void) {}
//EXPORT_C void ekern_54(void) {}
EXPORT_C void ekern_55(void) {}
//EXPORT_C void ekern_56(void) {}
EXPORT_C void ekern_57(void) {}
EXPORT_C void ekern_58(void) {}
EXPORT_C void ekern_59(void) {}
//EXPORT_C void ekern_60(void) {}
EXPORT_C void ekern_61(void) {}
EXPORT_C void ekern_62(void) {}
//EXPORT_C void ekern_63(void) {}
//EXPORT_C void ekern_64(void) {}
EXPORT_C void ekern_65(void) {}
EXPORT_C void ekern_66(void) {}
EXPORT_C void ekern_67(void) {}
EXPORT_C void ekern_68(void) {}
EXPORT_C void ekern_69(void) {}
//EXPORT_C void ekern_70(void) {}
//EXPORT_C void ekern_71(void) {}
//EXPORT_C void ekern_72(void) {}
//EXPORT_C void ekern_73(void) {}
//EXPORT_C void ekern_74(void) {}
//EXPORT_C void ekern_75(void) {}
//EXPORT_C void ekern_76(void) {}
EXPORT_C void ekern_77(void) {}
EXPORT_C void ekern_78(void) {}
EXPORT_C void ekern_79(void) {}
EXPORT_C void ekern_80(void) {}
EXPORT_C void ekern_81(void) {}
//EXPORT_C void ekern_82(void) {}
//EXPORT_C void ekern_83(void) {}
EXPORT_C void ekern_84(void) {}
EXPORT_C void ekern_85(void) {}
EXPORT_C void ekern_86(void) {}
EXPORT_C void ekern_87(void) {}
EXPORT_C void ekern_88(void) {}
EXPORT_C void ekern_89(void) {}
EXPORT_C void ekern_90(void) {}
EXPORT_C void ekern_91(void) {}
EXPORT_C void ekern_92(void) {}
EXPORT_C void ekern_93(void) {}
EXPORT_C void ekern_94(void) {}
EXPORT_C void ekern_95(void) {}
EXPORT_C void ekern_96(void) {}
EXPORT_C void ekern_97(void) {}
EXPORT_C void ekern_98(void) {}
EXPORT_C void ekern_99(void) {}
EXPORT_C void ekern_100(void) {}
EXPORT_C void ekern_101(void) {}
//EXPORT_C void ekern_102(void) {}
EXPORT_C void ekern_103(void) {}
//EXPORT_C void ekern_104(void) {}
EXPORT_C void ekern_105(void) {}
EXPORT_C void ekern_106(void) {}
EXPORT_C void ekern_107(void) {}
EXPORT_C void ekern_108(void) {}
EXPORT_C void ekern_109(void) {}
EXPORT_C void ekern_110(void) {}
EXPORT_C void ekern_111(void) {}
EXPORT_C void ekern_112(void) {}
//EXPORT_C void ekern_113(void) {}
//EXPORT_C void ekern_114(void) {}
//EXPORT_C void ekern_115(void) {}
//EXPORT_C void ekern_116(void) {}
//EXPORT_C void ekern_117(void) {}
//EXPORT_C void ekern_118(void) {}
EXPORT_C void ekern_119(void) {}
EXPORT_C void ekern_120(void) {}
EXPORT_C void ekern_121(void) {}
EXPORT_C void ekern_122(void) {}
EXPORT_C void ekern_123(void) {}
EXPORT_C void ekern_124(void) {}
EXPORT_C void ekern_125(void) {}
//EXPORT_C void ekern_126(void) {}
EXPORT_C void ekern_127(void) {}
EXPORT_C void ekern_128(void) {}
EXPORT_C void ekern_129(void) {}
EXPORT_C void ekern_130(void) {}
EXPORT_C void ekern_131(void) {}
EXPORT_C void ekern_132(void) {}
EXPORT_C void ekern_133(void) {}
//EXPORT_C void ekern_134(void) {}
//EXPORT_C void ekern_135(void) {}
EXPORT_C void ekern_136(void) {}
EXPORT_C void ekern_137(void) {}
//EXPORT_C void ekern_138(void) {}
//EXPORT_C void ekern_139(void) {}
//EXPORT_C void ekern_140(void) {}
//EXPORT_C void ekern_141(void) {}
//EXPORT_C void ekern_142(void) {}
//EXPORT_C void ekern_143(void) {}
//EXPORT_C void ekern_144(void) {}
EXPORT_C void ekern_145(void) {}
EXPORT_C void ekern_146(void) {}
EXPORT_C void ekern_147(void) {}
//EXPORT_C void ekern_148(void) {}
//EXPORT_C void ekern_149(void) {}
//EXPORT_C void ekern_150(void) {}
//EXPORT_C void ekern_151(void) {}
EXPORT_C void ekern_152(void) {}
//EXPORT_C void ekern_153(void) {}
EXPORT_C void ekern_154(void) {}
EXPORT_C void ekern_155(void) {}
//EXPORT_C void ekern_156(void) {}
EXPORT_C void ekern_157(void) {}
EXPORT_C void ekern_158(void) {}
EXPORT_C void ekern_159(void) {}
EXPORT_C void ekern_160(void) {}
EXPORT_C void ekern_161(void) {}
EXPORT_C void ekern_162(void) {}
EXPORT_C void ekern_163(void) {}
EXPORT_C void ekern_164(void) {}
//EXPORT_C void ekern_165(void) {}
//EXPORT_C void ekern_166(void) {}
EXPORT_C void ekern_167(void) {}
//EXPORT_C void ekern_168(void) {}
EXPORT_C void ekern_169(void) {}
EXPORT_C void ekern_170(void) {}
EXPORT_C void ekern_171(void) {}
EXPORT_C void ekern_172(void) {}
EXPORT_C void ekern_173(void) {}
EXPORT_C void ekern_174(void) {}
EXPORT_C void ekern_175(void) {}
EXPORT_C void ekern_176(void) {}
EXPORT_C void ekern_177(void) {}
EXPORT_C void ekern_178(void) {}
EXPORT_C void ekern_179(void) {}
EXPORT_C void ekern_180(void) {}
EXPORT_C void ekern_181(void) {}
EXPORT_C void ekern_182(void) {}
EXPORT_C void ekern_183(void) {}
EXPORT_C void ekern_184(void) {}
//EXPORT_C void ekern_185(void) {}
EXPORT_C void ekern_186(void) {}
//EXPORT_C void ekern_187(void) {}
//EXPORT_C void ekern_188(void) {}
//EXPORT_C void ekern_189(void) {}
EXPORT_C void ekern_190(void) {}
EXPORT_C void ekern_191(void) {}
EXPORT_C void ekern_192(void) {}
EXPORT_C void ekern_193(void) {}
EXPORT_C void ekern_194(void) {}
EXPORT_C void ekern_195(void) {}
EXPORT_C void ekern_196(void) {}
EXPORT_C void ekern_197(void) {}
EXPORT_C void ekern_198(void) {}
EXPORT_C void ekern_199(void) {}
EXPORT_C void ekern_200(void) {}
EXPORT_C void ekern_201(void) {}
EXPORT_C void ekern_202(void) {}
EXPORT_C void ekern_203(void) {}
//EXPORT_C void ekern_204(void) {}
//EXPORT_C void ekern_205(void) {}
EXPORT_C void ekern_206(void) {}
//EXPORT_C void ekern_207(void) {}
//EXPORT_C void ekern_208(void) {}
//EXPORT_C void ekern_209(void) {}
EXPORT_C void ekern_210(void) {}
EXPORT_C void ekern_211(void) {}
//EXPORT_C void ekern_212(void) {}
EXPORT_C void ekern_213(void) {}
EXPORT_C void ekern_214(void) {}
EXPORT_C void ekern_215(void) {}
//EXPORT_C void ekern_216(void) {}
EXPORT_C void ekern_217(void) {}
EXPORT_C void ekern_218(void) {}
EXPORT_C void ekern_219(void) {}
EXPORT_C void ekern_220(void) {}
EXPORT_C void ekern_221(void) {}
EXPORT_C void ekern_222(void) {}
EXPORT_C void ekern_223(void) {}
EXPORT_C void ekern_224(void) {}
EXPORT_C void ekern_225(void) {}
EXPORT_C void ekern_226(void) {}
EXPORT_C void ekern_227(void) {}
EXPORT_C void ekern_228(void) {}
EXPORT_C void ekern_229(void) {}
EXPORT_C void ekern_230(void) {}
EXPORT_C void ekern_231(void) {}
EXPORT_C void ekern_232(void) {}
//EXPORT_C void ekern_233(void) {}
EXPORT_C void ekern_234(void) {}
//EXPORT_C void ekern_235(void) {}
EXPORT_C void ekern_236(void) {}
EXPORT_C void ekern_237(void) {}
EXPORT_C void ekern_238(void) {}
EXPORT_C void ekern_239(void) {}
EXPORT_C void ekern_240(void) {}
EXPORT_C void ekern_241(void) {}
EXPORT_C void ekern_242(void) {}
EXPORT_C void ekern_243(void) {}
//EXPORT_C void ekern_244(void) {}
//EXPORT_C void ekern_245(void) {}
//EXPORT_C void ekern_246(void) {}
//EXPORT_C void ekern_247(void) {}
EXPORT_C void ekern_248(void) {}
//EXPORT_C void ekern_249(void) {}
EXPORT_C void ekern_250(void) {}
EXPORT_C void ekern_251(void) {}
EXPORT_C void ekern_252(void) {}
EXPORT_C void ekern_253(void) {}
EXPORT_C void ekern_254(void) {}
EXPORT_C void ekern_255(void) {}
EXPORT_C void ekern_256(void) {}
EXPORT_C void ekern_257(void) {}
EXPORT_C void ekern_258(void) {}
//EXPORT_C void ekern_259(void) {}
EXPORT_C void ekern_260(void) {}
EXPORT_C void ekern_261(void) {}
//EXPORT_C void ekern_262(void) {}
EXPORT_C void ekern_263(void) {}
EXPORT_C void ekern_264(void) {}
EXPORT_C void ekern_265(void) {}
//EXPORT_C void ekern_266(void) {}
EXPORT_C void ekern_267(void) {}
//EXPORT_C void ekern_268(void) {}
EXPORT_C void ekern_269(void) {}
//EXPORT_C void ekern_270(void) {}
EXPORT_C void ekern_271(void) {}
EXPORT_C void ekern_272(void) {}
EXPORT_C void ekern_273(void) {}
EXPORT_C void ekern_274(void) {}
EXPORT_C void ekern_275(void) {}
EXPORT_C void ekern_276(void) {}
EXPORT_C void ekern_277(void) {}
EXPORT_C void ekern_278(void) {}
EXPORT_C void ekern_279(void) {}
EXPORT_C void ekern_280(void) {}
EXPORT_C void ekern_281(void) {}
EXPORT_C void ekern_282(void) {}
EXPORT_C void ekern_283(void) {}
EXPORT_C void ekern_284(void) {}
EXPORT_C void ekern_285(void) {}
EXPORT_C void ekern_286(void) {}
EXPORT_C void ekern_287(void) {}
EXPORT_C void ekern_288(void) {}
EXPORT_C void ekern_289(void) {}
//EXPORT_C void ekern_290(void) {}
EXPORT_C void ekern_291(void) {}
//EXPORT_C void ekern_292(void) {}
//EXPORT_C void ekern_293(void) {}
//EXPORT_C void ekern_294(void) {}
EXPORT_C void ekern_295(void) {}
EXPORT_C void ekern_296(void) {}
EXPORT_C void ekern_297(void) {}
EXPORT_C void ekern_298(void) {}
//EXPORT_C void ekern_299(void) {}
EXPORT_C void ekern_300(void) {}
EXPORT_C void ekern_301(void) {}
EXPORT_C void ekern_302(void) {}
//EXPORT_C void ekern_303(void) {}
//EXPORT_C void ekern_304(void) {}
EXPORT_C void ekern_305(void) {}
EXPORT_C void ekern_306(void) {}
EXPORT_C void ekern_307(void) {}
//EXPORT_C void ekern_308(void) {}
//EXPORT_C void ekern_309(void) {}
EXPORT_C void ekern_310(void) {}
//EXPORT_C void ekern_311(void) {}
//EXPORT_C void ekern_312(void) {}
//EXPORT_C void ekern_313(void) {}
EXPORT_C void ekern_314(void) {}
EXPORT_C void ekern_315(void) {}
EXPORT_C void ekern_316(void) {}
EXPORT_C void ekern_317(void) {}
EXPORT_C void ekern_318(void) {}
EXPORT_C void ekern_319(void) {}
EXPORT_C void ekern_320(void) {}
EXPORT_C void ekern_321(void) {}
//EXPORT_C void ekern_322(void) {}
//EXPORT_C void ekern_323(void) {}
//EXPORT_C void ekern_324(void) {}
//EXPORT_C void ekern_325(void) {}
EXPORT_C void ekern_326(void) {}
EXPORT_C void ekern_327(void) {}
//EXPORT_C void ekern_328(void) {}
EXPORT_C void ekern_329(void) {}
EXPORT_C void ekern_330(void) {}
EXPORT_C void ekern_331(void) {}
//EXPORT_C void ekern_332(void) {}
EXPORT_C void ekern_333(void) {}
EXPORT_C void ekern_334(void) {}
EXPORT_C void ekern_335(void) {}
//EXPORT_C void ekern_336(void) {}
EXPORT_C void ekern_337(void) {}
//EXPORT_C void ekern_338(void) {}
//EXPORT_C void ekern_339(void) {}
EXPORT_C void ekern_340(void) {}
EXPORT_C void ekern_341(void) {}
EXPORT_C void ekern_342(void) {}
EXPORT_C void ekern_343(void) {}
EXPORT_C void ekern_344(void) {}
EXPORT_C void ekern_345(void) {}
EXPORT_C void ekern_346(void) {}
EXPORT_C void ekern_347(void) {}
EXPORT_C void ekern_348(void) {}
EXPORT_C void ekern_349(void) {}
EXPORT_C void ekern_350(void) {}
//EXPORT_C void ekern_351(void) {}
EXPORT_C void ekern_352(void) {}
EXPORT_C void ekern_353(void) {}
EXPORT_C void ekern_354(void) {}
//EXPORT_C void ekern_355(void) {}
//EXPORT_C void ekern_356(void) {}
EXPORT_C void ekern_357(void) {}
EXPORT_C void ekern_358(void) {}
EXPORT_C void ekern_359(void) {}
EXPORT_C void ekern_360(void) {}
EXPORT_C void ekern_361(void) {}
EXPORT_C void ekern_362(void) {}
EXPORT_C void ekern_363(void) {}
EXPORT_C void ekern_364(void) {}
EXPORT_C void ekern_365(void) {}
EXPORT_C void ekern_366(void) {}
EXPORT_C void ekern_367(void) {}
EXPORT_C void ekern_368(void) {}
EXPORT_C void ekern_369(void) {}
//EXPORT_C void ekern_370(void) {}
EXPORT_C void ekern_371(void) {}
EXPORT_C void ekern_372(void) {}
EXPORT_C void ekern_373(void) {}
//EXPORT_C void ekern_374(void) {}
EXPORT_C void ekern_375(void) {}
EXPORT_C void ekern_376(void) {}
EXPORT_C void ekern_377(void) {}
EXPORT_C void ekern_378(void) {}
EXPORT_C void ekern_379(void) {}
EXPORT_C void ekern_380(void) {}
EXPORT_C void ekern_381(void) {}
EXPORT_C void ekern_382(void) {}
EXPORT_C void ekern_383(void) {}
EXPORT_C void ekern_384(void) {}
EXPORT_C void ekern_385(void) {}
EXPORT_C void ekern_386(void) {}
EXPORT_C void ekern_387(void) {}
EXPORT_C void ekern_388(void) {}
EXPORT_C void ekern_389(void) {}
EXPORT_C void ekern_390(void) {}
EXPORT_C void ekern_391(void) {}
EXPORT_C void ekern_392(void) {}
EXPORT_C void ekern_393(void) {}
EXPORT_C void ekern_394(void) {}
//EXPORT_C void ekern_395(void) {}
EXPORT_C void ekern_396(void) {}
//EXPORT_C void ekern_397(void) {}
EXPORT_C void ekern_398(void) {}
EXPORT_C void ekern_399(void) {}
EXPORT_C void ekern_400(void) {}
EXPORT_C void ekern_401(void) {}
EXPORT_C void ekern_402(void) {}
EXPORT_C void ekern_403(void) {}
EXPORT_C void ekern_404(void) {}
EXPORT_C void ekern_405(void) {}
EXPORT_C void ekern_406(void) {}
EXPORT_C void ekern_407(void) {}
EXPORT_C void ekern_408(void) {}
EXPORT_C void ekern_409(void) {}
EXPORT_C void ekern_410(void) {}
EXPORT_C void ekern_411(void) {}
//EXPORT_C void ekern_412(void) {}
//EXPORT_C void ekern_413(void) {}
EXPORT_C void ekern_414(void) {}
EXPORT_C void ekern_415(void) {}
EXPORT_C void ekern_416(void) {}
EXPORT_C void ekern_417(void) {}
EXPORT_C void ekern_418(void) {}
EXPORT_C void ekern_419(void) {}
EXPORT_C void ekern_420(void) {}
EXPORT_C void ekern_421(void) {}
//EXPORT_C void ekern_422(void) {}
EXPORT_C void ekern_423(void) {}
EXPORT_C void ekern_424(void) {}
EXPORT_C void ekern_425(void) {}
EXPORT_C void ekern_426(void) {}
EXPORT_C void ekern_427(void) {}
EXPORT_C void ekern_428(void) {}
EXPORT_C void ekern_429(void) {}
EXPORT_C void ekern_430(void) {}
EXPORT_C void ekern_431(void) {}
EXPORT_C void ekern_432(void) {}
//EXPORT_C void ekern_433(void) {}
//EXPORT_C void ekern_434(void) {}
//EXPORT_C void ekern_435(void) {}
EXPORT_C void ekern_436(void) {}
EXPORT_C void ekern_437(void) {}
//EXPORT_C void ekern_438(void) {}
//EXPORT_C void ekern_439(void) {}
//EXPORT_C void ekern_440(void) {}
//EXPORT_C void ekern_441(void) {}
//EXPORT_C void ekern_442(void) {}
//EXPORT_C void ekern_443(void) {}
//EXPORT_C void ekern_444(void) {}
EXPORT_C void ekern_445(void) {}
EXPORT_C void ekern_446(void) {}
EXPORT_C void ekern_447(void) {}
//EXPORT_C void ekern_448(void) {}
EXPORT_C void ekern_449(void) {}
EXPORT_C void ekern_450(void) {}
EXPORT_C void ekern_451(void) {}
//EXPORT_C void ekern_452(void) {}
EXPORT_C void ekern_453(void) {}
EXPORT_C void ekern_454(void) {}
EXPORT_C void ekern_455(void) {}
EXPORT_C void ekern_456(void) {}
EXPORT_C void ekern_457(void) {}
EXPORT_C void ekern_458(void) {}
EXPORT_C void ekern_459(void) {}
EXPORT_C void ekern_460(void) {}
EXPORT_C void ekern_461(void) {}
EXPORT_C void ekern_462(void) {}
EXPORT_C void ekern_463(void) {}
//EXPORT_C void ekern_464(void) {}
EXPORT_C void ekern_465(void) {}
EXPORT_C void ekern_466(void) {}
EXPORT_C void ekern_467(void) {}
EXPORT_C void ekern_468(void) {}
EXPORT_C void ekern_469(void) {}
EXPORT_C void ekern_470(void) {}
EXPORT_C void ekern_471(void) {}
EXPORT_C void ekern_472(void) {}
EXPORT_C void ekern_473(void) {}
EXPORT_C void ekern_474(void) {}
//EXPORT_C void ekern_475(void) {}
EXPORT_C void ekern_476(void) {}
EXPORT_C void ekern_477(void) {}
//EXPORT_C void ekern_478(void) {}
//EXPORT_C void ekern_479(void) {}
//EXPORT_C void ekern_480(void) {}
EXPORT_C void ekern_481(void) {}
EXPORT_C void ekern_482(void) {}
EXPORT_C void ekern_483(void) {}
EXPORT_C void ekern_484(void) {}
EXPORT_C void ekern_485(void) {}
EXPORT_C void ekern_486(void) {}
EXPORT_C void ekern_487(void) {}
//EXPORT_C void ekern_488(void) {}
//EXPORT_C void ekern_489(void) {}
//EXPORT_C void ekern_490(void) {}
EXPORT_C void ekern_491(void) {}
EXPORT_C void ekern_492(void) {}
EXPORT_C void ekern_493(void) {}
EXPORT_C void ekern_494(void) {}
EXPORT_C void ekern_495(void) {}
EXPORT_C void ekern_496(void) {}
//EXPORT_C void ekern_497(void) {}
//EXPORT_C void ekern_498(void) {}
//EXPORT_C void ekern_499(void) {}
EXPORT_C void ekern_500(void) {}
//EXPORT_C void ekern_501(void) {}
//EXPORT_C void ekern_502(void) {}
EXPORT_C void ekern_503(void) {}
EXPORT_C void ekern_504(void) {}
EXPORT_C void ekern_505(void) {}
EXPORT_C void ekern_506(void) {}
